In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Make charts look cleaner
sns.set_style("whitegrid")
pd.set_option('display.max_columns', None)

print("Setup done!")

Setup done!

In [4]:
path = "olist_data/"

orders = pd.read_csv(path + "orders_dataset.csv")
order_items = pd.read_csv(path + "order_items_dataset.csv")
customers = pd.read_csv(path + "customers_dataset.csv")
sellers = pd.read_csv(path + "sellers_dataset.csv")
payments = pd.read_csv(path + "order_payments_dataset.csv")
reviews = pd.read_csv(path + "order_reviews_dataset.csv")
products = pd.read_csv(path + "products_dataset.csv")

print("Orders shape:", orders.shape)
print("Order items shape:", order_items.shape)
print("Customers shape:", customers.shape)
print("Sellers shape:", sellers.shape)
print("Payments shape:", payments.shape)
print("Reviews shape:", reviews.shape)
print("Products shape:", products.shape)

Orders shape: (99441, 8)
Order items shape: (112650, 7)
Customers shape: (99441, 5)
Sellers shape: (3095, 4)
Payments shape: (103886, 5)
Reviews shape: (100000, 7)
Products shape: (32951, 9)

In [5]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [6]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [7]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [8]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [9]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [10]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [11]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [12]:
# Step 1: Merge orders with customers (to get customer_unique_id and region)
df = orders.merge(customers, on="customer_id", how="left")

# Step 2: Merge in order_items (price, seller_id, product_id)
df = df.merge(order_items, on="order_id", how="left")

# Step 3: Merge in sellers (seller region)
df = df.merge(sellers, on="seller_id", how="left")

# Step 4: Merge in products (category)
df = df.merge(products, on="product_id", how="left")

# Step 5: Merge in payments (payment type, value)
df = df.merge(payments, on="order_id", how="left")

# Step 6: Merge in reviews (review score)
df = df.merge(reviews, on="order_id", how="left")

print("Master table shape:", df.shape)
df.head()

Master table shape: (119151, 39)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,9350.0,maua,SP,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,9350.0,maua,SP,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,9350.0,maua,SP,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,31570.0,belo horizonte,SP,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,14840.0,guariba,SP,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58

In [13]:
# Aggregate payments per order (sum all payment methods into one total per order)
payments_agg = payments.groupby("order_id").agg(
    total_payment_value=("payment_value", "sum"),
    payment_types_used=("payment_type", "nunique")
).reset_index()

payments_agg.head()

                           order_id  total_payment_value  payment_types_used
0  00010242fe8c5a6d1ba2dd792cb16214                72.19                   1
1  00018f77f2f0320c557190d7a144bdd3               259.83                   1
2  000229ec398224ef6ca0657da4fc703e               216.87                   1
3  00024acbcdf0a6daa1e931b038114c75                25.78                   1
4  00042b26cf59d7ce69dfabb4e55b4fd9               218.04                   1

In [14]:
# Rebuild master table with aggregated payments (no duplication)
df = orders.merge(customers, on="customer_id", how="left")
df = df.merge(order_items, on="order_id", how="left")
df = df.merge(sellers, on="seller_id", how="left")
df = df.merge(products, on="product_id", how="left")
df = df.merge(payments_agg, on="order_id", how="left")   # <-- using aggregated payments now
df = df.merge(reviews, on="order_id", how="left")

print("Master table shape:", df.shape)
df.head()

Master table shape: (114100, 37)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,total_payment_value,payment_types_used,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,9350.0,maua,SP,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,38.71,2.0,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,31570.0,belo horizonte,SP,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,141.46,1.0,8d5266042046a06655c8db133d120ba5,4,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,14840.0,guariba,SP,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,179.12,1.0,e73b67b67587f7644d5bd1a52deb1b01,5,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,1.0,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,31842.0,belo horizonte,MG,pet_shop,59.0,468.0,3.0,450.0,30.0,10.0,20.0,72.20,1.0,359d03e676b3c069f62cadba8dd3f6e8,5,NaN,O produto foi exatamente o que eu esperava e e...,2017-12-03 00:00:00,2017-12-05 19:21:58
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,1.0,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,8752.0,mogi das cruzes,SP,papelaria,38.0,316.0,4.0,250.0,51.0,15.0,15.0,28.62,1.0,e50934924e227544ba8246aeb3770dd4,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 13:02:51

In [15]:
date_cols = [
    "order_purchase_timestamp", "order_approved_at",
    "order_delivered_carrier_date", "order_delivered_customer_date",
    "order_estimated_delivery_date", "shipping_limit_date",
    "review_creation_date", "review_answer_timestamp"
]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")

print(df[date_cols].dtypes)

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
shipping_limit_date              datetime64[ns]
review_creation_date             datetime64[ns]
review_answer_timestamp          datetime64[ns]
dtype: object

In [17]:
print("Before filtering:", df.shape)
df = df[df["order_status"] == "delivered"].copy()
print("After filtering:", df.shape)

Before filtering: (110848, 37)
After filtering: (110848, 37)

In [18]:
df.isnull().sum().sort_values(ascending=False).head(15)

review_comment_title             97559
review_comment_message           63878
product_name_lenght               1545
product_category_name             1545
product_photos_qty                1545
product_description_lenght        1545
product_height_cm                   18
product_length_cm                   18
product_weight_g                    18
product_width_cm                    18
order_approved_at                   15
order_delivered_customer_date        8
total_payment_value                  3
payment_types_used                   3
order_delivered_carrier_date         2
dtype: int64

In [19]:
# Step 1: Get each customer's first purchase month (their "cohort")
df['order_month'] = df['order_purchase_timestamp'].dt.to_period('M')

first_purchase = df.groupby('customer_unique_id')['order_month'].min().reset_index()
first_purchase.columns = ['customer_unique_id', 'cohort_month']

df = df.merge(first_purchase, on='customer_unique_id', how='left')

df[['customer_unique_id', 'order_month', 'cohort_month']].head()

                 customer_unique_id order_month cohort_month
0  7c396fd4830fd04220f754e42b4e5bff     2017-10      2017-09
1  af07308b275d755c9edb36a90c618231     2018-07      2018-07
2  3a653a41f6f9fc3d2a113cf8398680e8     2018-08      2018-08
3  7c142cf63193a1473d2e66489a9ae977     2017-11      2017-11
4  72632f0f9dd73dfee390c9b22eb56dd6     2018-02      2018-02

In [20]:
# Calculate how many months after their first purchase this order happened
df['cohort_index'] = (df['order_month'] - df['cohort_month']).apply(lambda x: x.n)

df[['customer_unique_id', 'cohort_month', 'order_month', 'cohort_index']].head(10)

                 customer_unique_id cohort_month order_month  cohort_index
0  7c396fd4830fd04220f754e42b4e5bff      2017-09     2017-10             1
1  af07308b275d755c9edb36a90c618231      2018-07     2018-07             0
2  3a653a41f6f9fc3d2a113cf8398680e8      2018-08     2018-08             0
3  7c142cf63193a1473d2e66489a9ae977      2017-11     2017-11             0
4  72632f0f9dd73dfee390c9b22eb56dd6      2018-02     2018-02             0
5  80bb27c7c16e8f973207a5086ab329e2      2017-07     2017-07             0
6  932afa1e708222e5821dac9cd5db4cae      2017-05     2017-05             0
7  39382392765b6dc74812866ee5ee92a7      2017-01     2017-01             0
8  299905e3934e9e181bfb2e164dd4b4f8      2017-07     2017-07             0
9  f2a85dec752b8517b5e58a06ff3cd937      2017-05     2017-05             0

In [21]:
# Step 1: Count unique customers per cohort_month per cohort_index
cohort_data = df.groupby(['cohort_month', 'cohort_index'])['customer_unique_id'].nunique().reset_index()

# Step 2: Pivot it into a grid — rows = cohort month, columns = months since first purchase
cohort_table = cohort_data.pivot(index='cohort_month', columns='cohort_index', values='customer_unique_id')

cohort_table.head(10)

cohort_index,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20
cohort_month,,,,,,,,,,,,,,,,,,,,
2016-09,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-10,262.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0,2.0,2.0
2016-12,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01,717.0,2.0,2.0,1.0,3.0,1.0,3.0,1.0,1.0,NaN,3.0,1.0,5.0,3.0,1.0,1.0,2.0,3.0,1.0,NaN
2017-02,1628.0,3.0,5.0,2.0,7.0,2.0,4.0,3.0,2.0,3.0,2.0,5.0,2.0,3.0,2.0,1.0,1.0,3.0,NaN,NaN
2017-03,2503.0,11.0,9.0,10.0,9.0,4.0,4.0,8.0,8.0,2.0,9.0,3.0,5.0,3.0,4.0,6.0,2.0,3.0,NaN,NaN
2017-04,2256.0,14.0,5.0,4.0,6.0,6.0,8.0,7.0,7.0,4.0,6.0,2.0,1.0,1.0,2.0,2.0,3.0,NaN,NaN,NaN
2017-05,3451.0,16.0,16.0,10.0,10.0,11.0,14.0,5.0,9.0,9.0,9.0,12.0,8.0,1.0,6.0,7.0,NaN,NaN,NaN,NaN
2017-06,3037.0,15.0,12.0,13.0,9.0,12.0,11.0,7.0,4.0,6.0,9.0,11.0,5.0,5.0,7.0,NaN,NaN,NaN,NaN,NaN
2017-07,3752.0,20.0,13.0,9.0,11.0,8.0,12.0,4.0,7.0,10.0,8.0,11.0,5.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
# Get the size of each cohort (the cohort_index = 0 column = total customers who joined that month)
cohort_size = cohort_table.iloc[:, 0]

# Divide every column by the cohort size to get % retained
retention_table = cohort_table.divide(cohort_size, axis=0) * 100

retention_table.round(1).head(10)

cohort_index,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20
cohort_month,,,,,,,,,,,,,,,,,,,,
2016-09,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-10,100.0,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,0.4,NaN,0.4,NaN,0.4,NaN,0.4,NaN,0.4,0.8,0.8
2016-12,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01,100.0,0.3,0.3,0.1,0.4,0.1,0.4,0.1,0.1,NaN,0.4,0.1,0.7,0.4,0.1,0.1,0.3,0.4,0.1,NaN
2017-02,100.0,0.2,0.3,0.1,0.4,0.1,0.2,0.2,0.1,0.2,0.1,0.3,0.1,0.2,0.1,0.1,0.1,0.2,NaN,NaN
2017-03,100.0,0.4,0.4,0.4,0.4,0.2,0.2,0.3,0.3,0.1,0.4,0.1,0.2,0.1,0.2,0.2,0.1,0.1,NaN,NaN
2017-04,100.0,0.6,0.2,0.2,0.3,0.3,0.4,0.3,0.3,0.2,0.3,0.1,0.0,0.0,0.1,0.1,0.1,NaN,NaN,NaN
2017-05,100.0,0.5,0.5,0.3,0.3,0.3,0.4,0.1,0.3,0.3,0.3,0.3,0.2,0.0,0.2,0.2,NaN,NaN,NaN,NaN
2017-06,100.0,0.5,0.4,0.4,0.3,0.4,0.4,0.2,0.1,0.2,0.3,0.4,0.2,0.2,0.2,NaN,NaN,NaN,NaN,NaN
2017-07,100.0,0.5,0.3,0.2,0.3,0.2,0.3,0.1,0.2,0.3,0.2,0.3,0.1,0.2,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
import sqlite3

# Make a copy so we don't mess up our main df
df_sql = df.copy()

# Convert Period-type columns to plain text (SQLite can't store Period objects)
df_sql['order_month'] = df_sql['order_month'].astype(str)
df_sql['cohort_month'] = df_sql['cohort_month'].astype(str)

conn = sqlite3.connect(":memory:")
df_sql.to_sql("orders_master", conn, index=False, if_exists="replace")

query = """
SELECT product_category_name, COUNT(DISTINCT order_id) as total_orders
FROM orders_master
GROUP BY product_category_name
ORDER BY total_orders DESC
LIMIT 15
"""
pd.read_sql(query, conn)

     product_category_name  total_orders
0          cama_mesa_banho          9272
1             beleza_saude          8647
2            esporte_lazer          7530
3   informatica_acessorios          6530
4         moveis_decoracao          6307
5    utilidades_domesticas          5743
6       relogios_presentes          5495
7                telefonia          4093
8               automotivo          3810
9               brinquedos          3804
10              cool_stuff          3559
11      ferramentas_jardim          3448
12              perfumaria          3086
13                   bebes          2809
14             eletronicos          2517

In [26]:
# Step 1: Get each customer's FIRST purchase category (the category that brought them in)
first_category = df.sort_values('order_purchase_timestamp').groupby('customer_unique_id').first()['product_category_name'].reset_index()
first_category.columns = ['customer_unique_id', 'first_category']

# Step 2: Merge this back so every row knows what category the customer STARTED with
df = df.merge(first_category, on='customer_unique_id', how='left')

# Step 3: Count total orders per customer, split by their first_category
orders_per_customer = df.groupby(['customer_unique_id', 'first_category'])['order_id'].nunique().reset_index()
orders_per_customer.columns = ['customer_unique_id', 'first_category', 'total_orders']

# Step 4: For each first_category, calculate % of customers who ordered MORE than once
repeat_by_category = orders_per_customer.groupby('first_category').apply(
    lambda x: (x['total_orders'] > 1).mean() * 100
).reset_index()
repeat_by_category.columns = ['first_category', 'repeat_rate_pct']

repeat_by_category.sort_values('repeat_rate_pct', ascending=False).head(15)

C:\Users\misth\AppData\Local\Temp\ipykernel_13952\992904127.py:13: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  repeat_by_category = orders_per_customer.groupby('first_category').apply(

                   first_category  repeat_rate_pct
46                     la_cuisine        18.181818
37  fashion_roupa_infanto_juvenil        16.666667
4              artes_e_artesanato        15.789474
36         fashion_roupa_feminina         8.823529
28               eletrodomesticos         8.740741
52      moveis_colchao_e_estofado         8.333333
38        fashion_roupa_masculina         6.930693
56                  moveis_quarto         6.172840
33    fashion_bolsas_e_acessorios         5.771496
34               fashion_calcados         5.263158
19                   climatizacao         4.661017
54               moveis_decoracao         4.593043
13                cama_mesa_banho         4.563129
15                casa_conforto_2         4.545455
57                    moveis_sala         4.392765

In [27]:
# Add customer count per category to check reliability of the % 
category_counts = orders_per_customer.groupby('first_category')['customer_unique_id'].nunique().reset_index()
category_counts.columns = ['first_category', 'num_customers']

repeat_by_category = repeat_by_category.merge(category_counts, on='first_category')
repeat_by_category.sort_values('repeat_rate_pct', ascending=False).head(15)

                   first_category  repeat_rate_pct  num_customers
46                     la_cuisine        18.181818             11
37  fashion_roupa_infanto_juvenil        16.666667              6
4              artes_e_artesanato        15.789474             19
36         fashion_roupa_feminina         8.823529             34
28               eletrodomesticos         8.740741            675
52      moveis_colchao_e_estofado         8.333333             36
38        fashion_roupa_masculina         6.930693            101
56                  moveis_quarto         6.172840             81
33    fashion_bolsas_e_acessorios         5.771496           1698
34               fashion_calcados         5.263158            228
19                   climatizacao         4.661017            236
54               moveis_decoracao         4.593043           5922
13                cama_mesa_banho         4.563129           8744
15                casa_conforto_2         4.545455             22
57                    moveis_sala         4.392765            387

In [28]:
# For each seller, get: first sale date, last sale date, total number of orders, total revenue
seller_summary = df.groupby('seller_id').agg(
    first_sale=('order_purchase_timestamp', 'min'),
    last_sale=('order_purchase_timestamp', 'max'),
    total_orders=('order_id', 'nunique'),
    total_revenue=('price', 'sum'),
    avg_review_score=('review_score', 'mean')
).reset_index()

seller_summary.head(10)

,seller_id,first_sale,last_sale,total_orders,total_revenue,avg_review_score
0,0015a82c2db000af6aaaf3ae2ecb0532,2017-09-26 22:17:05,2017-10-18 08:16:34,3,2685.00,3.666667
1,001cca7ae9ae17fb1caed9dfb1094831,2017-02-04 19:06:04,2018-07-12 21:38:26,195,24487.03,3.935897
2,002100f778ceb8431b7a1020ff7ab48f,2017-09-14 01:00:31,2018-04-12 12:58:23,50,1236.50,4.036364
3,003554e2dce176b5555353e4f3555ac8,2017-12-15 06:52:25,2017-12-15 06:52:25,1,120.00,5.000000
4,004c9cd9d87a3c30c522c48c4fc07416,2017-01-27 10:34:34,2018-05-03 11:13:38,156,20407.19,4.108571
5,00720abe85ba0859807595bbf045a33b,2018-01-27 13:46:31,2018-08-03 16:57:01,13,1007.50,3.653846
6,00ab3eff1b5192e5f1a63bcecfee11c8,2017-03-18 11:40:26,2017-03-18 11:40:26,1,98.00,5.000000
7,00d8b143d12632bad99c0ad66ad52825,2018-03-21 11:17:37,2018-03-21 11:17:37,1,86.00,5.000000
8,00ee68308b45bc5e2660cd833c3f81cc,2017-09-19 01:02:44,2018-08-09 20:45:10,135,20345.00,4.335260
9,00fc707aaaad2d31347cf883cd2dfe10,2018-01-31 15:33:18,2018-06-13 16:19:00,103,13490.80,3.720280

In [29]:
# What's the most recent date in the entire dataset? (our reference point for "today")
max_date = df['order_purchase_timestamp'].max()
print("Most recent date in dataset:", max_date)

# Days since each seller's last sale (as of the end of our data)
seller_summary['days_since_last_sale'] = (max_date - seller_summary['last_sale']).dt.days

# Seller's "lifespan" — how many days between their first and last sale
seller_summary['seller_lifespan_days'] = (seller_summary['last_sale'] - seller_summary['first_sale']).dt.days

seller_summary.head(10)

Most recent date in dataset: 2018-08-29 15:00:37

,seller_id,first_sale,last_sale,total_orders,total_revenue,avg_review_score,days_since_last_sale,seller_lifespan_days
0,0015a82c2db000af6aaaf3ae2ecb0532,2017-09-26 22:17:05,2017-10-18 08:16:34,3,2685.00,3.666667,315,21
1,001cca7ae9ae17fb1caed9dfb1094831,2017-02-04 19:06:04,2018-07-12 21:38:26,195,24487.03,3.935897,47,523
2,002100f778ceb8431b7a1020ff7ab48f,2017-09-14 01:00:31,2018-04-12 12:58:23,50,1236.50,4.036364,139,210
3,003554e2dce176b5555353e4f3555ac8,2017-12-15 06:52:25,2017-12-15 06:52:25,1,120.00,5.000000,257,0
4,004c9cd9d87a3c30c522c48c4fc07416,2017-01-27 10:34:34,2018-05-03 11:13:38,156,20407.19,4.108571,118,461
5,00720abe85ba0859807595bbf045a33b,2018-01-27 13:46:31,2018-08-03 16:57:01,13,1007.50,3.653846,25,188
6,00ab3eff1b5192e5f1a63bcecfee11c8,2017-03-18 11:40:26,2017-03-18 11:40:26,1,98.00,5.000000,529,0
7,00d8b143d12632bad99c0ad66ad52825,2018-03-21 11:17:37,2018-03-21 11:17:37,1,86.00,5.000000,161,0
8,00ee68308b45bc5e2660cd833c3f81cc,2017-09-19 01:02:44,2018-08-09 20:45:10,135,20345.00,4.335260,19,324
9,00fc707aaaad2d31347cf883cd2dfe10,2018-01-31 15:33:18,2018-06-13 16:19:00,103,13490.80,3.720280,76,133

In [30]:
# Define churn: no sale in the last 90 days (relative to the most recent date in the dataset)
seller_summary['is_churned'] = seller_summary['days_since_last_sale'] > 90

# Overall churn rate
churn_rate = seller_summary['is_churned'].mean() * 100
print(f"Overall seller churn rate: {churn_rate:.1f}%")

# How many sellers only ever made ONE sale, ever?
one_time_sellers = (seller_summary['total_orders'] == 1).mean() * 100
print(f"Sellers who made only 1 sale ever: {one_time_sellers:.1f}%")

seller_summary['is_churned'].value_counts()

Overall seller churn rate: 39.4%
Sellers who made only 1 sale ever: 18.0%

is_churned
False    1801
True     1169
Name: count, dtype: int64

In [31]:
# Compare churned vs active sellers across key metrics
comparison = seller_summary.groupby('is_churned').agg(
    avg_total_orders=('total_orders', 'mean'),
    avg_total_revenue=('total_revenue', 'mean'),
    avg_review_score=('avg_review_score', 'mean'),
    avg_lifespan_days=('seller_lifespan_days', 'mean'),
    num_sellers=('seller_id', 'count')
).reset_index()

comparison

,is_churned,avg_total_orders,avg_total_revenue,avg_review_score,avg_lifespan_days,num_sellers
0,False,47.435314,6274.750461,4.191142,221.516380,1801
1,True,10.597092,1693.988529,4.050717,112.977759,1169

The trap: Data Leakage

In [32]:
# Get all order-level data joined with each seller's first_sale date
seller_orders = df.merge(seller_summary[['seller_id', 'first_sale']], on='seller_id')

# Keep only orders that happened within the seller's first 90 days
seller_orders['days_since_seller_start'] = (seller_orders['order_purchase_timestamp'] - seller_orders['first_sale']).dt.days
early_orders = seller_orders[seller_orders['days_since_seller_start'] <= 90]

# Build early-activity features per seller
early_features = early_orders.groupby('seller_id').agg(
    orders_first_90days=('order_id', 'nunique'),
    revenue_first_90days=('price', 'sum'),
    avg_review_first_90days=('review_score', 'mean'),
    avg_freight_first_90days=('freight_value', 'mean')
).reset_index()

early_features.head()

,seller_id,orders_first_90days,revenue_first_90days,avg_review_first_90days,avg_freight_first_90days
0,0015a82c2db000af6aaaf3ae2ecb0532,3,2685.00,3.666667,21.020000
1,001cca7ae9ae17fb1caed9dfb1094831,30,4582.80,3.659091,24.157727
2,002100f778ceb8431b7a1020ff7ab48f,31,661.50,4.085714,14.216571
3,003554e2dce176b5555353e4f3555ac8,1,120.00,5.000000,19.380000
4,004c9cd9d87a3c30c522c48c4fc07416,31,5218.14,4.325000,17.455750

In [33]:
model_data = seller_summary[['seller_id', 'is_churned', 'seller_lifespan_days']].merge(
    early_features, on='seller_id', how='left'
)

# Only keep sellers who've had enough time to be fairly judged (active for 90+ days OR already churned)
model_data = model_data[model_data['seller_lifespan_days'] >= 90].copy()

# Fill any missing early-activity values with 0 (sellers with no early activity recorded)
model_data = model_data.fillna(0)

print(model_data.shape)
model_data.head()

(1680, 7)

,seller_id,is_churned,seller_lifespan_days,orders_first_90days,revenue_first_90days,avg_review_first_90days,avg_freight_first_90days
1,001cca7ae9ae17fb1caed9dfb1094831,False,523,30,4582.80,3.659091,24.157727
2,002100f778ceb8431b7a1020ff7ab48f,True,210,31,661.50,4.085714,14.216571
4,004c9cd9d87a3c30c522c48c4fc07416,True,461,31,5218.14,4.325000,17.455750
5,00720abe85ba0859807595bbf045a33b,False,188,7,439.70,3.846154,13.543077
8,00ee68308b45bc5e2660cd833c3f81cc,False,324,34,4076.00,4.523810,18.706905

In [34]:
from sklearn.model_selection import train_test_split

# Features (X) and target label (y)
features = ['orders_first_90days', 'revenue_first_90days', 'avg_review_first_90days', 'avg_freight_first_90days']
X = model_data[features]
y = model_data['is_churned']

# Split: 80% to train the model, 20% to test how well it actually works on unseen data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Training set size:", X_train.shape)
print("Test set size:", X_test.shape)
print("\nChurn rate in training set:", y_train.mean())
print("Churn rate in test set:", y_test.mean())

Training set size: (1344, 4)
Test set size: (336, 4)

Churn rate in training set: 0.3013392857142857
Churn rate in test set: 0.3005952380952381

Logistic Regression model

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# Scale features (Logistic Regression works better when features are on a similar scale)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the model
log_model = LogisticRegression(random_state=42)
log_model.fit(X_train_scaled, y_train)

# Predict on the test set
y_pred = log_model.predict(X_test_scaled)

print("Model trained!")

Model trained!

In [36]:
from sklearn.metrics import classification_report, confusion_matrix

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[235   0]
 [101   0]]

Classification Report:
              precision    recall  f1-score   support

       False       0.70      1.00      0.82       235
        True       0.00      0.00      0.00       101

    accuracy                           0.70       336
   macro avg       0.35      0.50      0.41       336
weighted avg       0.49      0.70      0.58       336

C:\Users\misth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\misth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\misth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [37]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
rf_model.fit(X_train, y_train)  # Random Forest doesn't need scaled features

y_pred_rf = rf_model.predict(X_test)

print("Random Forest Results:")
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf, zero_division=0))

Random Forest Results:
[[203  32]
 [ 84  17]]
              precision    recall  f1-score   support

       False       0.71      0.86      0.78       235
        True       0.35      0.17      0.23       101

    accuracy                           0.65       336
   macro avg       0.53      0.52      0.50       336
weighted avg       0.60      0.65      0.61       336

In [38]:
# For each seller, find the date of their SECOND order (if they had one)
seller_order_dates = seller_orders.sort_values('order_purchase_timestamp').groupby('seller_id')['order_purchase_timestamp'].apply(list).reset_index()

def days_to_second(dates):
    if len(dates) < 2:
        return None  # never got a 2nd order
    return (dates[1] - dates[0]).days

seller_order_dates['days_to_second_order'] = seller_order_dates['order_purchase_timestamp'].apply(days_to_second)

# Merge into model_data
model_data = model_data.merge(seller_order_dates[['seller_id', 'days_to_second_order']], on='seller_id', how='left')

# Fill sellers who never got a 2nd order with a large number (999 = "never")
model_data['days_to_second_order'] = model_data['days_to_second_order'].fillna(999)

model_data[['seller_id', 'is_churned', 'days_to_second_order']].head(10)

                          seller_id  is_churned  days_to_second_order
0  001cca7ae9ae17fb1caed9dfb1094831       False                  14.0
1  002100f778ceb8431b7a1020ff7ab48f        True                   7.0
2  004c9cd9d87a3c30c522c48c4fc07416        True                   2.0
3  00720abe85ba0859807595bbf045a33b       False                   0.0
4  00ee68308b45bc5e2660cd833c3f81cc       False                   5.0
5  00fc707aaaad2d31347cf883cd2dfe10       False                   0.0
6  013900e863eace745d3ec7614cab5b1a        True                  23.0
7  014c0679dd340a0e338872e7ec85666a       False                  24.0
8  014d9a685fd57276679edd00e07089e5       False                  40.0
9  0176f73cc1195f367f7b32db1e5b3aa8       False                   8.0

In [39]:
# Update feature list to include the new feature
features = ['orders_first_90days', 'revenue_first_90days', 'avg_review_first_90days', 
            'avg_freight_first_90days', 'days_to_second_order']

X = model_data[features]
y = model_data['is_churned']

# Re-split (same random_state so it's a fair comparison to before)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Retrain Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

print("Random Forest Results (with days_to_second_order):")
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf, zero_division=0))

Random Forest Results (with days_to_second_order):
[[208  27]
 [ 81  20]]
              precision    recall  f1-score   support

       False       0.72      0.89      0.79       235
        True       0.43      0.20      0.27       101

    accuracy                           0.68       336
   macro avg       0.57      0.54      0.53       336
weighted avg       0.63      0.68      0.64       336

In [40]:
import pandas as pd

feature_importance = pd.DataFrame({
    'feature': features,
    'importance': rf_model.feature_importances_
}).sort_values('importance', ascending=False)

feature_importance

                    feature  importance
1      revenue_first_90days    0.262423
3  avg_freight_first_90days    0.243769
4      days_to_second_order    0.181709
2   avg_review_first_90days    0.165773
0       orders_first_90days    0.146327

In [41]:
# Flag whether each customer ever placed more than 1 order (repeat buyer)
customer_repeat = df.groupby('customer_unique_id')['order_id'].nunique().reset_index()
customer_repeat.columns = ['customer_unique_id', 'total_orders']
customer_repeat['is_repeat_buyer'] = customer_repeat['total_orders'] > 1

# Get each customer's FIRST order's price and freight (their initial experience)
first_order_data = df.sort_values('order_purchase_timestamp').groupby('customer_unique_id').first()[['price', 'freight_value']].reset_index()

# Merge repeat flag with first-order price/freight
freight_analysis = customer_repeat.merge(first_order_data, on='customer_unique_id')

# Calculate freight as a % of price (how "expensive" shipping felt relative to the item)
freight_analysis['freight_pct_of_price'] = (freight_analysis['freight_value'] / freight_analysis['price']) * 100

freight_analysis.head()

,customer_unique_id,total_orders,is_repeat_buyer,price,freight_value,freight_pct_of_price
0,0000366f3b9a7992bf8c76cfdf3221e2,1,False,129.90,12.00,9.237875
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,False,18.90,8.29,43.862434
2,0000f46a3911fa3c0805444483337064,1,False,69.00,17.22,24.956522
3,0000f6ccb0745a6a4b88665a16c9f078,1,False,25.99,17.63,67.833782
4,0004aac84e0df4da2b147fca70cf8255,1,False,180.00,16.89,9.383333

In [42]:
comparison = freight_analysis.groupby('is_repeat_buyer').agg(
    avg_freight_value=('freight_value', 'mean'),
    avg_price=('price', 'mean'),
    avg_freight_pct=('freight_pct_of_price', 'mean'),
    num_customers=('customer_unique_id', 'count')
).reset_index()

comparison

,is_repeat_buyer,avg_freight_value,avg_price,avg_freight_pct,num_customers
0,False,20.223582,126.546474,30.800242,90557
1,True,18.733345,105.565627,32.586803,2801

power bi

In [43]:
# 1. Retention table (for the retention curve chart)
retention_table.reset_index().to_csv("retention_table.csv", index=False)

# 2. Category repeat-rate table (filtered to reliable sample sizes only)
repeat_by_category[repeat_by_category['num_customers'] >= 100].to_csv("category_repeat_rates.csv", index=False)

# 3. Seller summary (for seller churn/revenue visuals)
seller_summary.to_csv("seller_summary.csv", index=False)

# 4. Feature importance (for the ML insight visual)
feature_importance.to_csv("feature_importance.csv", index=False)

print("All files exported!")

All files exported!

In [44]:
import os
print(os.getcwd())

C:\Users\misth\OneDrive\Desktop\Brazilian E-Commerce Public Dataset by Olist

In [45]:
# Reshape retention_table from wide to long format for Power BI
retention_long = retention_table.reset_index().melt(
    id_vars='cohort_month', 
    var_name='months_since_first_purchase', 
    value_name='retention_pct'
)

retention_long.to_csv("retention_table_long.csv", index=False)
retention_long.head(10)

  cohort_month months_since_first_purchase  retention_pct
0      2016-09                           0          100.0
1      2016-10                           0          100.0
2      2016-12                           0          100.0
3      2017-01                           0          100.0
4      2017-02                           0          100.0
5      2017-03                           0          100.0
6      2017-04                           0          100.0
7      2017-05                           0          100.0
8      2017-06                           0          100.0
9      2017-07                           0          100.0